name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🚀 Sync Files
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Upload to cPanel via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server: ${{ secrets.FTP_HOST }}
        port: 22 # <-- Connects securely via SFTP port
        local_path: './*' # <-- Uploads everything from your repository
        remote_path: ${{ secrets.FTP_DIR }}
